Added test to verify login with valid and invalid creds
marynast/RF-Marina pull request #1
Opened 2021-06-17 10:06 UTC by marynast

2021-06-17 13:53 UTC, codci requested changes

2021-06-17 13:53 UTC, codci commented on Resources/PageObject/WeatherApp.robot
> +*** Settings ***
В одном модуле PageObject реализуется взаимодействие сразу с несколькими страницами

2021-06-17 13:53 UTC, codci commented on Resources/PageObject/WeatherApp.robot
> +${MainPage_SignInButton_Locator}  //a[text()="Sign in"]
локатор находит 2 элемента (один из которых скрыт). 
Локаторы должны находить только один уникальный элемент (в лучах кнопок текстовых полей и т.д.) и опираться на свойства которые не будут меняться (либо будут но не так часто) 

попробуй использовать относительные локаторы для поиска: например для данного элемента следующий локатор найдет только одно совпадение и будет более надежным: `//div[@id="desktop-menu"]//a[text()="Sign in"]`

2021-06-17 13:53 UTC, codci commented on Resources/PageObject/WeatherApp.robot
> +${URL}  https://openweathermap.org
данная переменная будет общей для всего ресурса, так что ее лучше расположить в файле который будет доступен для всех страниц и использовать его

2021-06-17 13:53 UTC, codci commented on Resources/PageObject/WeatherApp.robot
> +    Sleep    5s
плохая практика использовать слипы, вместо этого везде где возможно старайся ожидать какого либо события

2021-06-17 13:53 UTC, codci commented on Resources/PageObject/WeatherApp.robot
> +    Click Element    ${MainPage_SignInButton_Locator}
перед нажатием на элементы хорошей практикой будет проверять что элемент готов к тому чтобы на него нажимали :)

2021-06-17 14:11 UTC, codci commented on Resources/PageObject/WeatherApp.robot
> +    Element Text Should Be    ${SignIn_AlertText_Locator}  ${AlertText}
Отсутствует проверка что пользователь авторизован/не авторизован в системе

2021-06-21 19:08 UTC, marynast commented on Resources/PageObject/WeatherApp.robot
> +*** Settings ***
created separate files in PageObject module

2021-06-21 19:08 UTC, marynast commented on Resources/PageObject/WeatherApp.robot
> +${MainPage_SignInButton_Locator}  //a[text()="Sign in"]
changed the locator into //div[@id="desktop-menu"]//a[text()="Sign in"]

2021-06-21 19:10 UTC, marynast commented on Resources/PageObject/WeatherApp.robot
> +    Sleep    5s
used `Wait Until Element Is Not Visible    ${MainPage_Loader_Locator}  timeout=30s` instead of Sleep

2021-06-21 19:11 UTC, marynast commented on Resources/PageObject/WeatherApp.robot
> +    Click Element    ${MainPage_SignInButton_Locator}
added checks for all elements which we interact with

2021-06-21 19:12 UTC, marynast commented on Resources/PageObject/WeatherApp.robot
> +    Element Text Should Be    ${SignIn_AlertText_Locator}  ${AlertText}
login state check was added

2021-06-21 19:14 UTC, marynast commented on Resources/PageObject/WeatherApp.robot
> +${URL}  https://openweathermap.org
moved to Resources/General.robot

2021-06-28 08:27 UTC, codci commented on Resources/PageObject/WeatherApp-SignInPage.robot
> +    IF    "${AlertText}" == "${InvalidCredentials_AlertText}"
Тут проблема с логикой проверки: непонятно почему мы тут привязаны к алерту, что если мы захотим проверить состояние авторизации после других действий не делая логин до этого. Нам нельзя в кейвордах завязываться на предыдущие действия (это как с зависимостью тестов).

Если цель проверить что пользователь залогинен - надо проверять состояние страницы когда пользователь авторизован. т.е. проверять что у нас есть профиль либо его нету (если усложнять логику) 

*лучше не использовать элементы (переменные) из другого модуля без необходимости.

2021-06-28 08:30 UTC, merged