Homework3
marynast/RF-Marina pull request #2
Opened 2021-06-24 18:07 UTC by marynast

2021-06-28 09:01 UTC, codci requested changes

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +    IF    "${AlertText}" == "${InvalidCredentials_AlertText}"
Тут проблема с логикой проверки: непонятно почему мы тут привязаны к алерту, что если мы захотим проверить состояние авторизации после других действий не делая логин до этого. Нам нельзя в кейвордах завязываться на предыдущие действия (это как с зависимостью тестов).

Если цель проверить что пользователь залогинен - надо проверять состояние страницы когда пользователь авторизован. т.е. проверять что у нас есть профиль либо его нету (если усложнять логику)

*лучше не использовать элементы (переменные) из другого модуля без необходимости.

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/General.robot
> +Resource  /Users/marina/Python/development/robot-scripts/RF-Marina/WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
абсолютный путь

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/General.robot
> +${URL}  https://openweathermap.org/
УРЛ такой же как и HomePage_URL

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/General.robot
> +Go to Main Page
лучше закинуть это в Main Page

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/General.robot
> +Go to Sign In Page
лучше закинуть это в Sign In Page

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +Select "My Profile" From The Dropdown List In Navigation Menu
как отработает метод если дропдаун уже открыт

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +    Click Element    ${NavigationMenu_UserDropdown_MyProfile_Locator}
лучше в таких случаях (навигация по пунктам меню) делать более универсальными и передавать пункт меню который надо выбрать. Иначе тебе придется писать n-одинаковых методов для разных пунктов

переделай данный метод чтобы можно было передать какой пункт меню выбирать

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Tests/Weather-Authorization.robot
> +    [Setup]  Run Keywords
обрати внимание на синтаксис Run Keywords когда передаются аргументы в выполняемый кейворд (с использованием AND)  - https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keywords

Просто для информации

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Tests/Weather-UserSettings.robot
> +    UserProfilePage.Click "Save" button At User Profile Page And Verify The Alert Text
действие и проверки в одном кейворде, будет очень сложно переиспользовать его.

2021-06-28 09:01 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +Verify New User Name Is Displayed In The Navigation Menu
название кейворда выглядит как что-то очень специфичное

2021-06-29 16:38 UTC, marynast commented on WeatherApp/Desktop/Resources/General.robot
> +${URL}  https://openweathermap.org/
removed HomePage_URL

2021-06-29 16:44 UTC, marynast commented on WeatherApp/Desktop/Resources/General.robot
> +Go to Main Page
moved keywords "Go to Main Page" and "Go to Sign In Page" to Main page and Sign in Page

2021-06-29 17:51 UTC, marynast commented on WeatherApp/Desktop/Tests/Weather-UserSettings.robot
> +    UserProfilePage.Click "Save" button At User Profile Page And Verify The Alert Text
split into two separate keywords

2021-07-02 08:41 UTC, codci requested changes

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/MainPage.robot
> +${URL}  https://openweathermap.org/
URL лучше вынести в глобальный конфиг, с большой вероятностью ты его будешь переиспользовать на других страницах / кейвордах

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +    ${UserDropdownIsVisible}=  Run Keyword And Return Status   Element Should Not Be Visible   ${NavigationMenu_UserDropdown_Locator}
нейминг переменных

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +    ...             Open User Dropdown List In Navigation Menu
логику проверки состояния дропдауна лучше перенести в `Open User Dropdown List In Navigation Menu` - из названия я понимаю что этот кейворд должны открыть дропдаун, но получается что он только нажимает на него а логику проверки открытия мы должны реализовывать в другом месте

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +    [Arguments]  ${NewUsername}
аргумент все равно странный =)

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +${SignInPage_URL}                               https://home.openweathermap.org/users/sign_in
лучше переиспользовать переменную  `HomePage_URL`:
${HomePage_URL}users/sign_in

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +    [Arguments]  ${Username}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +    [Arguments]  ${Password}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +    [Arguments]  ${AlertText}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +    [Arguments]  ${LoginStatus}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/SignInPage.robot
> +${FailedLogin}                                  ${SignIn_NavigationMenu_SignInButton_Locator}
очень странные переменные

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/UserProfilePage.robot
> +    [Arguments]  ${NewUsername}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/UserProfilePage.robot
> +    [Arguments]  ${MyProfile_ProfileUpdatedSuccessAlert_Text}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/UserProfilePage.robot
> +    [Arguments]  ${MyProfile_ProfileUpdatedSuccessAlert_Text}
название очень длинной и непонятное

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +Resource   ../../../Desktop_Imports.robot
предлагаю вынести импорты в init.robot и в файлах импортировать только его, это поможет избежать длинных путей

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +    [Arguments]    ${Username}    ${Password}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +    [Arguments]    ${AlertText}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +    SignInPage.Verify Alert Text    ${AlertText}
перед проверкой текста, я бы проверил что Алерт отображается на странице

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +    [Arguments]    ${LoginStatus}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +    [Arguments]    ${Username}    ${Password}    ${AlertText}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/LoginStep.robot
> +User Is Logged In
название немного странное, нам лучше указывать что делает метод, а тут как утверждение, я бы подумал о ренейминге

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/UserSettingsStep.robot
> +    [Arguments]  ${NavigationMenuUserDropdownOptions}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/UserSettingsStep.robot
> +    [Arguments]  ${NewUsername}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/UserSettingsStep.robot
> +    [Arguments]  ${MyProfile_ProfileUpdatedSuccessAlert_Text}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/UserSettingsStep.robot
> +    NavigationMenu.Click Option In User Dropdown List    ${NavigationMenuUserDropdownOptions}
поговорим об этом методе

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/UI/UserSettingsStep.robot
> +    [Arguments]  ${NewUsername}
стиль локальной переменной

2021-07-02 08:41 UTC, codci commented on WeatherApp/Desktop/Tests/Weather-Authorization.robot
> +*** Settings ***
давай попробуем добавить лог степов в тесты как мы начали делать в айве

2021-07-05 08:35 UTC, codci requested changes

2021-07-05 08:35 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/MainPage.robot
> +${URL}  https://openweathermap.org/
так а тут надо удалить его тогда)

2021-07-05 08:35 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/NavigationMenu.robot
> +         Skip
блок Else можно не писать если в нем ничего не происходит

2021-07-05 08:35 UTC, codci commented on WeatherApp/Desktop/Resources/General.robot
> +${URL}                           https://openweathermap.org/
HomePage_URL в другом файле, нужно бы в одно место складывать

2021-07-05 08:35 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/UserProfilePage.robot
> +    [Arguments]  ${NewUsername}
ловеркейс?

2021-07-05 08:35 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/LoginStep.robot
> +Resource  __init__.robot
__init__.robot не позволяет делать импорт :( 
нужно использовать ресурс файлы - давай создадим вместо импорта resource.robot в  WeatherApp/Desktop/Resources/Steps и туда перенесем импорт ресурсов из инит файла

2021-07-05 12:25 UTC, codci approved these changes

2021-07-05 12:26 UTC, merged