API tests
marynast/RF-Marina pull request #3
Opened 2021-07-07 11:56 UTC by marynast

Added API tests
Updated requirements.txt

2021-07-08 17:56 UTC, codci commented on WeatherApp/Desktop/Resources/API-Keywords.robot
> +    Status Should Be    200
смотри у тебя везде повторяются строки выполнения запроса, давай его вынесем чтобы не дублировать их

2021-07-08 17:56 UTC, codci commented on WeatherApp/Desktop/Resources/API-Keywords.robot
> +*** Settings ***
мне не очень нравится что ты в кейворде делаем "степ" - я бы разделил действие и проверку

2021-07-08 17:56 UTC, codci commented on WeatherApp/Desktop/Tests/API-CurrentWeather.robot
> +    [Template]   API-Keywords.Get current weather by city name and verify the unit of temperature
теплейте лучше ложить в файле с тестом, т.к это и есть тест который принимает разные данные и не будет переиспользован в других тестах

2021-08-16 08:04 UTC, codci requested changes

2021-08-16 08:04 UTC, codci commented on WeatherApp/Convert.py
> +def round_the_float(self):
нет смысла в таком методе если мы не расширяем стандартный метод

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +    ${response_json}=  Get Current Weather By City ID Via API    ${city_id}    ${api_key}
${city_id} ${api_key} - должны быть глобальными переменными, очень большой шанс допустить ошибку

нужно явно передавать переменные в кейворды

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +    ${response_json}=  Get Current Weather By Coordinates Via API    ${latitude}    ${longitude}    ${api_key}
${latitude} ${longitude} ${api_key} - должны быть глобальными переменными, очень большой шанс допустить ошибку

нужно явно передавать переменные в кейворды

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +    ${response_json}=  Get Current Weather By City Name And Unit Of Measurement    ${city_name}    ${temperature_unit}    ${api_key}
${city_name} ${temperature_unit} ${api_key}  - должны быть глобальными переменными, очень большой шанс допустить ошибку

нужно явно передавать переменные в кейворды

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +    ${response_json}=  Get Current Weather By City Name Via API    ${city_name}    ${api_key}
${city_name} ${api_key} - должны быть глобальными переменными, очень большой шанс допустить ошибку

нужно явно передавать переменные в кейворды

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +     ${response_json}=  Get Current Weather By City Name Via API    ${city_name}    ${api_key}
${city_name} ${api_key} - должны быть глобальными переменными, очень большой шанс допустить ошибку

нужно явно передавать переменные в кейворды

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/General.robot
> +${APIKey}                        68320938aa1059333e2a94e89bf98b5e
ну нельзя такое хардкодить =)

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/MainPage.robot
> +${MainPage_DropdownCityOption_Locator}  //span[contains(text(),'${city_name}')]
если переменная будет не определена тест упадет

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/PageObject/MainPage.robot
> +    Return From Keyword  ${current_temperature_web.strip(${measurement_unit_code})}
лучше конвертировать в [Return] - чтобы было в общем стиле (и добавит читабельности)

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/FindWeatherStep.robot
> +Send Get Current Weather By City Name And Unit Of Measurement And Get Temperature In Fahrenheit
очень длинное имя

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/Steps/FindWeatherStep.robot
> +Send Get Current Weather By City Name Via API And Get Temperature In Celsius
очень длинное имя

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +     ${temperature_value}=  Round The Float    ${temperature_value}
округление долго использоваться там где нам нужно округленное значение (в кейворде проверки) 
что делать если нам понадобится проверить что значение через аги возвращается правильное?

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +Get Temperature Value From Response In Fahrenheit
в чем отличие этого кейворда от Get Temperature Value From Response In Celsius?

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +Get Current Weather By City Name And Unit Of Measurement
в чем отличие этого кейворда от Get Current Weather By City Name Via API

2021-08-16 08:04 UTC, codci commented on WeatherApp/Desktop/Tests/API-CurrentWeather.robot
> +    [Documentation]  API test to get the current weather by city name, coordinates or City Id and verify the response
Добавить получение ${APIKey} в прекондишн

2021-08-18 10:00 UTC, marynast commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +Get Current Weather By City Name And Unit Of Measurement
removed 'Get Current Weather By City Name And Unit Of Measurement' and added unit of measurement to 'Get Current Weather By City Name Via API'

2021-08-20 15:49 UTC, marynast commented on WeatherApp/Convert.py
> +def round_the_float(self):
removed method. numbers are rounded in Verify step

2021-08-20 15:50 UTC, marynast commented on WeatherApp/Desktop/Resources/API/API-Keywords.robot
> +Get Temperature Value From Response In Fahrenheit
combined into one keyword

2021-09-01 08:06 UTC, codci approved these changes

2021-09-01 08:06 UTC, merged